### PR TITLE
Add `ls` function

### PR DESCRIPTION
**Pull request by isaacseymour**
Hey @tdcain89, thanks for the fab wrapper! This would be a really useful addition for us 😄

### CODE REVIEW

**Comment by tdcain89** [comment]
@isaacseymour Thanks for the PR! I'm going to take a look at this later today and probably merge. 

We're actually using this in production... I had hoped to release this to hex before we launched our app but ran out of time. If I can finish the docs/specs for this I'll see if I can release to hex in the next couple of weeks.

**Comment by isaacseymour** [comment]
Awesome, that would be much nicer than using it via git 😄 

How are you running the specs? They seem to require an ftp server running on localhost?

**Comment by tdcain89** [comment]
I think that was my main reason for skipping tests the first time around... didn't really have a solid plan for testing.

**Comment by isaacseymour** [comment]
Fair enough - I was mostly wondering how you'd go about testing something like this in Elixir!

**Comment by tdcain89** [comment]
@isaacseymour This looks good! One change for now... can you add an additional error map to `FTPoison.Error` ? Looks like if you do `FTPoison.list(pid, "path_that_does_not_exist")` we get the following error:

```
(FTPoison.Error) got nil while retrieving Exception.message/1 for %FTPoison.Error{reason: :enofile} (expected a string)
```

Just need to add something like

```
enofile: "No such file or directory."
```

After that I'll merge and possibly start working on cleaning tests up this week. Thanks again!

**Comment by isaacseymour** [comment]
@tdcain89 updated. Good spot! Annoyingly, the docs (specifically [here](http://erlang.org/doc/man/ftp.html#id78699)) don't exhaustively specify the possible errors:

``` erlang
common_reason() = econn | eclosed | term() 
```

😡

**Pull request merged**
